[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.11"
dependencies = [
    "flask",
    "paper-qa>=5.0",
    "python-dotenv",
    "flask-cors",
    "gunicorn",
    "lancedb",
    "openai"
]